MOD renamed `axis` meta-Data field to `orientation
runtastic/Matrioska pull request #18
Opened 2017-03-09 13:43 UTC by AndreasThenn

2017-03-09 14:30 UTC, ktraunmueller commented on Source/Components/StackCluster.swift
> +            if "horizontal" == orientationRawValue {
We should maybe introduce an enum with (`String`-valued) raw values for this and use the failable initializer to map strings onto enumeration cases.

Something like this:
```
var axis = UILayoutConstraintAxis.vertical
if let orientationRawValue = meta["orientation"] as? String,
   let orientation = Orientation(rawValue: orientationRawValue) {
     axis = orientation.layoutConstraintAxis
}
```
with
```
public enum ClusterLayout {
    
    public enum Orientation: String {
        case horizontal
        case vertical
    }
}

extension ClusterLayout.Orientation {
    
    var layoutConstraintAxis: UILayoutConstraintAxis {
        switch self {
        case .horizontal: return .horizontal
        case .vertical: return .vertical
        }
    }
}
```

2017-03-09 15:04 UTC, AndreasThenn commented on Source/Components/StackCluster.swift
> +            if "horizontal" == orientationRawValue {
I like your approach, I tried to get the String name of out of UILayoutConstraintAxis, but that did not work. I updated the PR

2017-03-09 15:31 UTC, ktraunmueller approved these changes

2017-03-10 09:12 UTC, ChristianOrgler approved these changes
Please adapt any example .json files from axis to orientation.

2017-03-10 09:12 UTC, ChristianOrgler commented on Source/Components/StackCluster.swift
> +            if let orientationRawValue = meta["orientation"] as? String,
don't you need to adapt the example json as well?

2017-03-10 09:20 UTC, AndreasThenn commented on Source/Components/StackCluster.swift
> +            if let orientationRawValue = meta["orientation"] as? String,
It uses already `orientation`

2017-03-10 17:26 UTC, mathiasAichinger approved these changes

2017-03-11 09:03 UTC, joanromano requested changes
Please update the `StackClusterTests` where using a dictionary (`ComponentMeta`); those tests are still using `axis` but they pass because .vertical is now the default value when parsing. Adding a new test with this new `orientation` String value would have helped here. And I would really rethink about the need of that new `Orientation` enum.

But more importantly, please update the JSON schema guide https://github.com/runtastic/Matrioska/blob/master/Documentation/JSON%20schema%20guide.md otherwise it's reflecting wrong information.

2017-03-11 09:03 UTC, joanromano commented on Source/Components/ClusterLayout.swift
> +    }
I am not sure if this information belongs here: afaik the `ClusterLayout` public enum is an enumeration to add new clusters, and the orientation is something that is not used in all of them.

Plus, I don't find this enum useful to be exposed publicly. When would this be used? As it is right now is only used by the library to parse the `ComponentMeta` into a `ExpressibleByComponentMeta` stack config. I would keep this thing internal to the library somewhere else if you really need to use it (which maybe we don't really need it for now).

2017-03-11 09:03 UTC, joanromano commented on Source/Components/StackCluster.swift
> +            }
If it's only for this, I don't think a `Orientation` enum is helpful for now. I would remove it and do the parsing normally as with the other fields

2017-03-11 09:06 UTC, MP0w commented on Source/Components/StackCluster.swift
> +            }
+1 is not something helpful for other Components

2017-03-12 12:04 UTC, ChristianOrgler commented on Source/Components/ClusterLayout.swift
> +    }
I agree 👍

2017-03-13 14:57 UTC, ktraunmueller commented on Source/Components/ClusterLayout.swift
> +    }
Right, good point.

2017-03-13 15:03 UTC, ktraunmueller commented on Source/Components/StackCluster.swift
> +            }
Agreed, no need to expose that. Maybe make it a private type (of `StackCluster`)?

2017-03-13 15:22 UTC, joanromano commented on Source/Components/StackCluster.swift
> +            }
If you really think it's useful to keep it for the parsing ok, yes I would keep it private.

2017-03-13 16:11 UTC, AndreasThenn commented on Source/Components/StackCluster.swift
> +            }
thx for the feedback, @joanromano I updated my PR

2017-03-13 16:29 UTC, joanromano commented on Source/Components/StackCluster.swift
> +            }
Thanks, please don't forget to update the tests and the JSON schema guide as mentioned above.

2017-03-13 22:05 UTC, joanromano requested changes
Please update `StackClusterTests`, I believe there are tests using `axis` in their `ComponentMeta` and they pass just because we test against the default value.

2017-03-14 07:34 UTC, AndreasThenn commented
@joanromano thx, indeed one test just passed because it used default value. I modified it to use orientation and added a new one to not use the default value. I added a new one, because the horizontal orientation of the first one just looked really ugly. Please check if you're fine with the new setup.

2017-03-15 14:28 UTC, joanromano approved these changes

2017-03-15 15:04 UTC, merged