FIX swift3.1 compiler error when implementing subscript on a dictionary
runtastic/Matrioska pull request #21
Opened 2017-03-28 12:59 UTC by AndreasThenn

2017-03-28 13:35 UTC, AndreasThenn commented
FYI solution based on https://github.com/apple/swift-evolution/blob/master/proposals/0141-available-by-swift-version.md

2017-03-30 14:58 UTC, ktraunmueller approved these changes

2017-03-31 08:34 UTC, ktraunmueller requested changes
This breaks existing code.

e.g. this code now early exits because `title` is `nil` although a corresponding entry is present in the dictionary:
```
init?(meta: ComponentMeta) {
    guard let title = meta["title"] as? String else {
        return nil
    }
```

Edit: sorry, false alarm; it's working with the `@available` attribute, but it breaks when removing the Dictionary extension in `ComponentMeta` (for some reason I don't understand).

2017-03-31 09:32 UTC, ktraunmueller approved these changes

2017-04-05 12:14 UTC, mathiasAichinger approved these changes

2017-04-05 12:15 UTC, merged